/* office master data */
INSERT INTO offices_master (office_code, office_name, address, post_code, city, country) VALUES ('SPR-CV', 'Ciutat Vella', 'address', '08015', 'Barcelona', 'Spain')
INSERT INTO offices_master (office_code, office_name, address, post_code, city, country) VALUES ('SPR-NB', 'Nou Barris', 'address', '08015', 'Barcelona', 'Spain')
INSERT INTO offices_master (office_code, office_name, address, post_code, city, country) VALUES ('SPR-HG', 'Horta-Guinardó', 'address', '08015', 'Barcelona', 'Spain')
INSERT INTO offices_master (office_code, office_name, address, post_code, city, country) VALUES ('SPR-SG', 'Sarrià-Sant Gervasi', 'address', '08015', 'Barcelona', 'Spain')
INSERT INTO offices_master (office_code, office_name, address, post_code, city, country) VALUES ('SPR-LC', 'Les Corts', 'address', '08015', 'Barcelona', 'Spain')
INSERT INTO offices_master (office_code, office_name, address, post_code, city, country) VALUES ('SPR-GR', 'Gracia', 'address', '08015', 'Barcelona', 'Spain')
INSERT INTO offices_master (office_code, office_name, address, post_code, city, country) VALUES ('SPR-SA', 'Sants', 'address', '08015', 'Barcelona', 'Spain')
INSERT INTO offices_master (office_code, office_name, address, post_code, city, country) VALUES ('SPR-SM', 'Sant-Martí', 'address', '08015', 'Barcelona', 'Spain')
INSERT INTO offices_master (office_code, office_name, address, post_code, city, country) VALUES ('SPR-SA', 'Sant Andreu', 'address', '08015', 'Barcelona', 'Spain')
/* category */
INSERT INTO categories (cod_category, price_base, price_base_insurance, price_top_insurance, price_tire_and_glass_protection) VALUES ('CAT_SUP', '100.0', '900.50', '1200.0', '300.0')
INSERT INTO categories (cod_category, price_base, price_base_insurance, price_top_insurance, price_tire_and_glass_protection) VALUES ('CAT_MED', '50.0', '90.50', '600.0', '50.0')
INSERT INTO categories (cod_category, price_base, price_base_insurance, price_top_insurance, price_tire_and_glass_protection) VALUES ('CAT_ECO', '25.0', '50.50', '300.0', '25.0')
/* cars master data*/
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('1', 'Audi A3 Cabrio', 'Audi', 'MANUAL', 'true', '4', '3','1','/images/cat_sup/audi-a3-cabrio-2d-weiss-offen.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('1', 'Mercedes-Benz Clase C', 'Mercedes', 'MANUAL', 'true', '5', '5','2','/images/cat_sup/mb-c-klasse-4d-silber.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('1', 'BMW Serie 2 Active Tourer', 'BMW', 'MANUAL', 'true', '5', '5','2','/images/cat_sup/bmw-2er-active-tourer-5d-blau.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('1', 'BMW Serie 3 SW', 'BMW', 'MANUAL', 'true', '5', '5','1','/images/cat_sup/bmw-3er-kombi-grau.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('1', 'BMW i8', 'BMW', 'AUTOMATIC', 'true', '2', '2','1','/images/cat_sup/bmw-i8-2d-weiss-us.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('1', 'BMW X1 Aut', 'BMW', 'AUTOMATIC', 'true', '5', '5','1','/images/cat_sup/bmw-x1-5d-weiss.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('1', 'Jaguar F-Type Coupé', 'Jaguar', 'AUTOMATIC', 'true', '2', '3','1','/images/cat_sup/jaguar-f-type-coupe-2d-silber.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('1', 'Mercedes-Benz Clase A Aut', 'Mercedes', 'AUTOMATIC', 'true', '5', '5','1','/images/cat_sup/mb-a-klasse-5d-weiss.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('1', 'Mercedes-Benz SLC Cabrio', 'Mercedes', 'MANUAL', 'true', '2', '3','1','/images/cat_sup/mb-slc-cabrio-2d-grau-offen.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('1', 'MINI One Cabrio', 'MINI', 'MANUAL', 'true', '4', '3','1','/images/cat_sup/mini-cooper-cabrio-2d-schwarz-offen.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('2', 'Citroën C4 Cactus Aut', 'Citroën', 'AUTOMATIC', 'true', '5', '5','1','/images/cat_med/citroen-c4-cactus-5d-weiss.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('2', 'MINI', 'MINI', 'MANUAL', 'true', '4', '3','1','/images/cat_med/mini-cooper-3d-schwarz.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('2', 'Opel Zafira', 'Opel', 'MANUAL', 'true', '5', '5','2','/images/cat_med/opel-zafira-5d-silber.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('2', 'Peugeot Partner', 'Peugeot', 'MANUAL', 'true', '5', '5','2','/images/cat_med/peugeot-partner-tepee-van-braun.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('2', 'VW Golf', 'VW', 'MANUAL', 'true', '5', '5','2','/images/cat_med/vw-golf-5d-weiss.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('2', 'VW Golf SW', 'VW', 'MANUAL', 'true', '5', '5','3','/images/cat_med/vw-golf-kombi-grau.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('2', 'VW Polo Aut', 'VW', 'AUTOMATIC', 'true', '4', '5','1','/images/cat_med/vw-polo-5d-schwarz.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('3', 'Ford Ka', 'Ford', 'MANUAL', 'true', '4', '3','1','/images/cat_eco/ford-ka-3d-blau.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('3', 'Opel Corsa', 'Opel', 'MANUAL', 'true', '5', '5','1','/images/cat_eco/opel-corsa-5d-weiss.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('3', 'Peugeot 308', 'Peugeot', 'MANUAL', 'true', '5', '5','1','/images/cat_eco/peugeot-308-5d-weiss.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('3', 'Smart Forfour', 'Smart', 'MANUAL', 'true', '4', '4','1','/images/cat_eco/smart-for-four-4d-lava.png')
INSERT INTO cars (category_id, model, marca, transmission, ac, seats, doors, suit_cases, photo) VALUES  ('3', 'VW Polo', 'VW', 'MANUAL', 'true', '5', '5','1','/images/cat_eco/vw-polo-5d-schwarz.png')
/* extras for test*/
INSERT INTO common_extras (description_extra, price) VALUES  ('Baby seat guaranteed (0-13kg / Group 0+)', '11.99')
INSERT INTO common_extras (description_extra, price) VALUES  ('Child seat guaranteed (9-36kg / Group 1/2/3)', '11.99')
INSERT INTO common_extras (description_extra, price) VALUES  ('Booster seat guaranteed (15 - 36kg / Group 2/3)', '9.99')
INSERT INTO common_extras (description_extra, price) VALUES  ('Snow chains', '18.33')
INSERT INTO common_extras (description_extra, price) VALUES  ('Ski & Snowboard rack', '18.33')
/*clients*/
INSERT INTO clients (name, surname, id_number, phone_number, email, address, city, country, user_name, password) VALUES ('Floren', 'Lopez', '53647852', '667854120', 'florentinolopez@gmail.com', 'C/ Roger de Lluria, 23','Sta Coloma de Gr', 'Spain', 'Flonchi', '3333')
INSERT INTO clients (name, surname, id_number, phone_number, email, address, city, country, user_name, password) VALUES ('Laura', 'García', '48569953', '688547412', 'lauris84@gmail.com', 'C/ Biscaia, 125','Barcelona', 'Spain', 'Lauriss', '2552')